name: Watch UR Vacancy

on:
  schedule:
    - cron: "*/10 * * * *" # 10分ごと（UTC）
  workflow_dispatch: # 手動実行も可

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          # 予備（手動の固定IDを併用したい場合のみ使用）
          LINE_USER_IDS: ${{ secrets.LINE_USER_IDS }}
        run: |
          python main.py
