name: Watch UR Vacancy

on:
  schedule:
    - cron: "*/10 * * * *" # 10分ごと（UTC基準）
  workflow_dispatch: # 手動実行も可

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          LINE_NOTIFY_TOKENS: ${{ secrets.LINE_NOTIFY_TOKENS }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          python main.py
